import React from 'react';

const datalistSuchworte = (
    <datalist id="Begriffe" className="hidden">
     <option value="Absetzbetrag"/>
     <option value="AG"/>
     <option value="Aktiengesellschaft"/>
     <option value="Alleinverdienerabsetzbetrag"/>
     <option value="Arbeiterkammerumlage"/>
     <option value="Altersteilzeit"/>
     <option value="Absetzung"/>
     <option value="BAO"/>
     <option value="Bemessungsgrundlage"/>
     <option value="Betrieb gewerblicher Art"/>
     <option value="Bundesabgabenordnung"/>
     <option value="Deponiesteuer"/>
     <option value="Dienstgeberabgabe"/>
     <option value="Eigenverbrauch"/>
     <option value="Einbringung"/>
     <option value="Einheitswert"/>
     <option value="Einkommensteuer" />
     <option value="Einkommensteuererklärung"/>
     <option value="EStG" />
     <option value="Familienbeihilfe"/>
     <option value="Freibetrag"/>
     <option value="FinanzOnline"/>
     <option value="Freiberufler"/>
     <option value="Freier Beruf"/>
     <option value="Gebrauchsabgabe"/>
     <option value="GesmbH"/>
     <option value="Getränkesteuer"/>
     <option value="Gewerbe"/>
     <option value="Gewerbebetrieb"/>
     <option value="GmbH"/>
     <option value="Grunderwerbsteuer"/>
     <option value="Grundfreibetrag"/>
     <option value="Grundsteuer"/>
     <option value="Halbsatzverfahren"/>
     <option value="Investitionszuwachsprämie"/>
     <option value="Jahressechstel"/>
     <option value="Kapitalertragssteuer"/>
     <option value="Kapitalvermögen"/>
     <option value="KESt"/>
     <option value="Kilometergeld"/>
     <option value="Kinderabsetzbetrag"/>
     <option value="KG"/>
     <option value="Kommanditgesellschaft"/>
     <option value="Kommanditist"/>
     <option value="Kommunalsteuer"/>
     <option value="Kraftfahrzeugsteuer"/>
     <option value="Landwirtschaft"/>
     <option value="Legitimationsprüfung"/>
     <option value="Leistungsfähigkeitsprinzip"/>
     <option value="Immobilienertragsteuer"/>
     <option value="ImmoESt"/>
     <option value="Lohnsteuer" />
     <option value="Luftsteuer"/>
     <option value="Mineralölsteuer"/>
     <option value="Motorbezogene Versicherungssteuer"/>
     <option value="Nettoprinzip"/>
     <option value="NoVA"/>
     <option value="Normverbrauchsabgabe"/>
     <option value="Offene Gesellschaft"/>
     <option value="OG"/>
     <option value="Organschaft"/>
     <option value="Pauschalierung"/>
     <option value="Pendlereuro"/>
     <option value="Pendlerpauschale"/>
     <option value="Pensionistenabsetzbetrag"/>
     <option value="Personengesellschaft"/>
     <option value="Quellensteuer"/>
     <option value="Privatstiftung"/>
     <option value="Registrierkasse"/>
     <option value="Reisekosten"/>
     <option value="Sonderausgaben"/>
     <option value="Sonstige Einkünfte"/>
     <option value="Stammkapital"/>
     <option value="Steuerabsetzbetrag"/>
     <option value="Steuerabsetzbeträge"/>
     <option value="Steuerschuldverhältnis"/>
     <option value="Stiftung"/>
     <option value="Umsatzsteuer"/>
     <option value="Unterhaltsabsetzbetrag"/>
     <option value="Vereinsrecht"/>
     <option value="Verkehrsabsetzbetrag"/>
     <option value="Verlustvortrag"/>
     <option value="Vermietung"/>
     <option value="Vermögenszuwachssteuer"/>
     <option value="Verpachtung"/>
     <option value="Waisenrente"/>
     <option value="Werbeabgabe"/>
     <option value="Werbungskosten"/>
     <option value="Wohnbausteuer"/>
    </datalist>
   );

export { datalistSuchworte };